name       : python-pyperclip
version    : 1.8.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/pyperclip/pyperclip-1.8.0.tar.gz : b75b975160428d84608c26edba2dec146e7799566aea42c1fe1b32e72b6028f2
homepage   : https://github.com/asweigart/pyperclip
license    : BSD 3-Clause
component  : programming.python
summary    : Python module for copying and pasting text to the clipboard.
description: |
    Pyperclip is a cross-platform Python module for copy and paste clipboard functions. This module makes use of the xclip or xsel commands.
builddeps  :
    - python-pytest
rundeps    :
    - xclip
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
